#spring:
#  application:
#    name: itoken-zipkin
#  boot:
#    admin:
#      client:
#        url: http://localhost:8084
#
#server:
#  port: 9411
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#management:
#  metrics:
#    web:
#      server:
#        auto-time-requests: false

spring:
  application:
    name: zipkin
  cloud:
    config:
      uri: http://localhost:8888
      name: zipkin
      label: master
      profile: dev