#spring:
#  application:
#    name: itoken-account-feign
#  boot:
#    admin:
#      client:
#        url: http://localhost:8084
#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#  zipkin:
#    base-url: http://localhost:9411
#
#server:
#  port: 8765
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: account-feign
  cloud:
    config:
      uri: http://localhost:8888
      name: account-feign
      label: master
      profile: dev
