#spring:
#  application:
#    name: itoken-account-provider
#  zipkin:
#    base-url: http://localhost:9411
#  boot:
#    admin:
#      client:
#        url: http://localhost:8084
#
#server:
#  port: 8762
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: account-provider
  cloud:
    config:
      uri: http://localhost:8888
      name: account-provider
      label: master
      profile: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/websocket?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1124
    driver-class-name: com.mysql.jdbc.Driver